apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
